---
- name: git clone
  become_user: isucon
  git:
    repo=https://github.com/catatsuy/isucon6-final.git
    dest=/home/isucon/repos
    accept_hostkey=yes
- name: remove webapp directory
  file:
    path=/home/isucon/webapp/
    state=absent
- name: move webapp directory
  command: "mv /home/isucon/repos/webapp /home/isucon/webapp"
- name: remove repos directory
  file:
    path=/home/isucon/repos/
    state=absent
- name: symoblic link docker-compose.yml
  become_user: isucon
  file:
    src=/home/isucon/webapp/docker-compose-php.yml
    dest=/home/isucon/webapp/docker-compose.yml
    state=link
- name: docker pull
  command: docker pull {{ item }}
  become_user: isucon
  with_items:
    - mysql
    - nginx:alpine
- name: docker build
  command: chdir="/home/isucon/webapp/{{ item }}" docker build .
  become_user: isucon
  with_items:
    - php
    - react
- name: place the file of systemd
  copy:
    src=etc/systemd/system/isu.service
    dest=/etc/systemd/system/isu.service
    owner=root
    mode=644
  notify: reload systemctl
- name: running default application
  service: name=isu state=restarted enabled=true
- pause: seconds=10
