---
- name: unarchive webapp directory
  unarchive: src=https://@AZURE_STORAGE_ACCOUNT@.blob.core.windows.net/@CONTAINER_NAME@/webapp.tar.gz dest=/home/isucon/ remote_src=yes
- name: symoblic link docker-compose.yml
  become_user: isucon
  file:
    src=/home/isucon/webapp/docker-compose-php.yml
    dest=/home/isucon/webapp/docker-compose.yml
    state=link
- name: remove .gitignore
  file:
    path=/home/isucon/webapp/.gitignore
    state=absent
- name: docker pull
  command: docker pull {{ item }}
  become_user: isucon
  with_items:
    - mysql
    - nginx:alpine
- name: docker build
  command: chdir="/home/isucon/webapp/{{ item }}" docker build .
  become_user: isucon
  with_items:
    - php
    - react
- name: place the file of systemd
  copy:
    src=etc/systemd/system/isu.service
    dest=/etc/systemd/system/isu.service
    owner=root
    mode=644
  notify: reload systemctl
- name: running default application
  service: name=isu state=restarted enabled=true
- pause: seconds=30
- name: set mysql data
  command: "{{ item }}"
  become_user: isucon
  with_items:
    - docker exec webapp_mysql_1 sh -c 'MYSQL_PWD=password mysql -uroot < /sql/create_database.sql'
    - docker exec webapp_mysql_1 sh -c 'MYSQL_PWD=password mysql -uroot -Disuchannel < /sql/schema.sql'
